version: 0.2
env:
    shell: powershell.exe
phases:
  install:
    commands:
      - Start-BitsTransfer -Source "https://builds.dotnet.microsoft.com/dotnet/Sdk/6.0.428/dotnet-sdk-6.0.428-win-x64.exe" -Destination ".\dotnet-sdk-6.0.428-win-x64.exe"
      - Start-Process -FilePath ".\dotnet-sdk-6.0.428-win-x64.exe" -ArgumentList "/quiet" -NoNewWindow -Wait
  build:
    commands:
      - cd ProfitCalc.Web
      - dotnet restore
      - dotnet build --configuration Release
      - $publish_artifact="..\deployment\app"
      - dotnet publish --configuration Release --output $publish_artifact

      # Copy appspec.yml and scripts folder into deployment package
      - Copy-Item "..\ProfitCalc.Web\appspec.yml" "..\deployment\appspec.yml"
      - Copy-Item "..\ProfitCalc.Web\scripts" "..\deployment\scripts" -Recurse

      # Optional: Clean up web.config if needed
      - Get-ChildItem -Path "$publish_artifact" -Filter "web.config" -Recurse | Remove-Item -Force

      # Zip the whole deployment folder
      - Compress-Archive -Path "..\deployment\*" -DestinationPath "..\deployment.zip" -Force
artifacts:
  files:
    - deployment.zip
